name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Update the revision property in pom.xml
        run: |
          sed -i "s|<revision>DEV-BUILD</revision>|<revision>${BUILD_VERSION}</revision>|g" pom.xml
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./target
          retention-days: 7
